// Instagram-inspired AONE direction: bold contrast, energetic coral, punchy typography, photo-led browsing, and fast booking moments.
import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight, Clock3, Instagram, MapPin, Menu, Phone, Sparkles, Star, Users, X } from "lucide-react";

const heroSlides = [
  { kicker: "A ONE UNISEX SALON & BEAUTY PARLOUR", title: "Hair that\ngets noticed.", copy: "Cuts, colour, care and confidence — all under one roof in Badlapur.", image: "/manus-storage/aone-hero_d342bf01.jpg", badge: "EST. 2023" },
  { kicker: "THE COLOUR ROOM", title: "Your next\nlook starts here.", copy: "From a fresh root touch-up to a full transformation, let’s make it yours.", image: "/manus-storage/aone-colour-detail_af7415c5.jpg", badge: "COLOUR / CARE" },
  { kicker: "CARE THAT SHOWS", title: "Come for the\nrefresh.", copy: "Leave feeling lighter, brighter and ready for whatever is next.", image: "/manus-storage/aone-interior_4f4202a6.jpg", badge: "BADLAPUR WEST" },
];

const menu = {
  "Women’s hair": { image: "/manus-storage/aone-colour-detail_af7415c5.jpg", accent: "#f06f61", intro: "Cuts, styling, colour and treatments made around your hair.", items: [["Basic Haircut + Styling", "₹499"], ["Advanced Haircut + Styling", "₹699"], ["Hair Styling — Iron/Curls", "₹599"], ["Global Colour", "₹2,999"], ["Balayage", "₹3,999"], ["Keratin — short", "₹4,999"]] },
  "Skin & beauty": { image: "/manus-storage/aone-hands-service_1dfc03b6.jpg", accent: "#ffb43b", intro: "Quick refreshes and feel-good rituals for your skin.", items: [["Basic Cleanup", "₹499"], ["Advance Cleanup", "₹999"], ["Aroma D-Tan", "₹499"], ["Eyebrows", "₹60"], ["Full Face Threading", "₹200"], ["Full Face Wax — regular", "₹300"]] },
  "Spa & nails": { image: "/manus-storage/aone-interior_4f4202a6.jpg", accent: "#a86cff", intro: "Slow down with a little care from head to toe.", items: [["Head Massage", "₹299"], ["Foot Massage — 20 min", "₹499"], ["Full Body Massage — 60 min", "₹1,399"], ["Basic Manicure", "₹499"], ["Premium Pedicure", "₹999"], ["Body Polishing", "₹2,999"]] },
  "Men’s grooming": { image: "/manus-storage/aone-hero_d342bf01.jpg", accent: "#48c6a8", intro: "Sharp cuts, beard care and everyday grooming, sorted.", items: [["Men’s Haircut", "₹199"], ["Kids Haircut", "₹149"], ["Shampoo & Styling", "₹149"], ["Dry Styling", "₹100"], ["Beard Trim/Shave", "₹149"], ["Beard Colour", "₹299"]] },
};

type Category = keyof typeof menu;
const categories = Object.keys(menu) as Category[];
const packages = [{ label: "WOMEN", title: "The occasion edit", copy: "Haircut + styling + root touch-up + nails + threading", price: "₹2,999", color: "yellow" }, { label: "MEN", title: "The clean-up", copy: "Haircut + hair wash + beard + D-Tan", price: "₹699", color: "mint" }, { label: "GROUPS", title: "Platinum people", copy: "Up to five family or friends, with VIP booking priority", price: "₹2,000 / year", color: "purple" }];

export default function Home() {
  const [slide, setSlide] = useState(0);
  const [category, setCategory] = useState<Category>("Women’s hair");
  const [menuOpen, setMenuOpen] = useState(false);
  const current = heroSlides[slide];
  useEffect(() => { const timer = window.setInterval(() => setSlide((n) => (n + 1) % heroSlides.length), 6500); return () => window.clearInterval(timer); }, []);
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  return <main className="instagram-shell">
    <div className="top-ticker"><span>BADLAPUR WEST’S UNISEX SALON & BEAUTY PARLOUR</span><span>NOW BOOKING <Sparkles size={13} /></span><span>EST. 2023</span></div>
    <header className="ig-header"><a className="ig-brand" href="#top"><span className="ig-mark"><img src="/manus-storage/aone-mark_e21acb3f.png" alt="" /></span><span>A ONE</span></a><nav className={menuOpen ? "ig-nav open" : "ig-nav"}><a href="#menu" onClick={() => setMenuOpen(false)}>Menu</a><a href="#packages" onClick={() => setMenuOpen(false)}>Offers</a><a href="#membership" onClick={() => setMenuOpen(false)}>Membership</a><a href="#contact" onClick={() => setMenuOpen(false)}>Find us</a></nav><div className="ig-head-actions"><a href="https://www.instagram.com/aone_salon_spa/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={18} /></a><button className="ig-book" onClick={() => go("contact")}>BOOK NOW <ArrowUpRight size={15} /></button></div><button className="ig-menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></header>

    <section className="ig-hero" id="top"><div className="hero-left"><div className="hero-kicker"><span />{current.kicker}</div><h1>{current.title.split("\n").map((line, i) => <span key={line} className={i === 1 ? "hero-pop" : ""}>{line}</span>)}</h1><p>{current.copy}</p><div className="hero-buttons"><button className="ig-book big" onClick={() => go("contact")}>BOOK YOUR APPOINTMENT <ArrowRight size={17} /></button><button className="outline-button" onClick={() => go("menu")}>SEE THE MENU</button></div><div className="hero-bottom"><span><Star size={15} fill="currentColor" /> 267+ local followers</span><span>Shop no. 1, Rameshwadi</span></div></div><div className="hero-right"><div className="hero-photo" style={{ backgroundImage: `url(${current.image})` }} /><div className="hero-sticker">{current.badge}<br /><b>♥</b></div><div className="hero-slide-control"><button onClick={() => setSlide((slide + heroSlides.length - 1) % heroSlides.length)} aria-label="Previous"><ChevronLeft /></button><strong>0{slide + 1}</strong><span>/ 03</span><button onClick={() => setSlide((slide + 1) % heroSlides.length)} aria-label="Next"><ChevronRight /></button></div><div className="hero-hashtag">#AONELOOK</div></div></section>

    <div className="ig-marquee"><div>HAIR <i>✦</i> SKIN <i>✦</i> SPA <i>✦</i> NAILS <i>✦</i> GROOMING <i>✦</i> HAIR <i>✦</i> SKIN <i>✦</i> SPA <i>✦</i> NAILS <i>✦</i> GROOMING <i>✦</i></div></div>

    <section className="ig-menu-section" id="menu"><div className="ig-section-intro"><div><span className="mini-label">01 / THE MENU</span><h2>Pick your<br /><b>mood.</b></h2></div><p>Scroll the categories, find your service, see the price. No mystery. Just good hair, good skin and a really good feeling.</p></div><div className="category-tabs">{categories.map((name) => <button key={name} className={category === name ? "active" : ""} onClick={() => setCategory(name)}><span>{name === category ? "✦" : "○"}</span>{name}</button>)}</div><div className="menu-showcase"><div className="menu-photo" style={{ backgroundImage: `url(${menu[category].image})` }}><div className="photo-bubble" style={{ backgroundColor: menu[category].accent }}>AONE<br /><b>CARE<br />CLUB</b></div><span className="photo-caption">{category.toUpperCase()} / AONE SALON</span></div><div className="menu-list"><div className="menu-list-head"><span>{menu[category].intro}</span><strong>{menu[category].items.length} highlights</strong></div>{menu[category].items.map(([name, price], i) => <div className="menu-line" key={name}><span className="line-number">0{i + 1}</span><strong>{name}</strong><span className="line-dots" /><b>{price}</b></div>)}<button className="menu-cta" onClick={() => go("contact")}>ASK FOR THE FULL MENU <ArrowUpRight size={16} /></button></div></div></section>

    <section className="why-section" id="about"><div className="why-card"><span className="mini-label">02 / WHY A ONE</span><h2>Your look.<br /><b>Your rules.</b></h2><p>A one unisex salon and beauty parlour, established in 2023. We do hair treatments, hair cutting, spa and more — with care that feels personal.</p><button className="white-button" onClick={() => go("contact")}>MEET A ONE <ArrowRight size={16} /></button></div><div className="why-photo" style={{ backgroundImage: "url(/manus-storage/aone-interior_4f4202a6.jpg)" }}><span>REAL PEOPLE.<br />REAL RESULTS.</span></div></section>

    <section className="offers-section" id="packages"><div className="offers-head"><div><span className="mini-label">03 / OFFERS & PACKAGES</span><h2>More care.<br /><b>More value.</b></h2></div><p>Make it a full day. Or make it a family thing. Our packages and plans keep the good energy going.</p></div><div className="offer-cards">{packages.map((item) => <article className={`offer-card ${item.color}`} key={item.title}><div className="offer-top"><span>{item.label}</span><ArrowUpRight size={18} /></div><div><h3>{item.title}</h3><p>{item.copy}</p></div><div className="offer-bottom"><strong>{item.price}</strong><button onClick={() => go("contact")}>ENQUIRE</button></div></article>)}</div></section>

    <section className="membership-section" id="membership"><div className="membership-copy"><span className="mini-label">04 / MEMBERSHIP</span><h2>Join the<br /><b>care club.</b></h2><p>Gold at ₹500/year or Platinum at ₹2,000/year. Save on services, get priority scheduling, and keep your AONE moments closer.</p><button className="ig-book" onClick={() => go("contact")}>ENQUIRE ABOUT MEMBERSHIP <ArrowUpRight size={15} /></button></div><div className="membership-poster"><div className="poster-star">✦</div><span>A ONE / MEMBERSHIP</span><strong>GOLD<br /><em>10% OFF</em></strong><small>ALL SERVICES · PRIORITY BOOKING · FESTIVE GIFT</small></div></section>

    <section className="contact-ig" id="contact"><div><span className="mini-label">05 / COME BY</span><h2>Let’s make<br /><b>an entrance.</b></h2><button className="ig-book big" onClick={() => go("contact")}>BOOK YOUR APPOINTMENT <ArrowRight size={17} /></button></div><div className="contact-details"><div className="contact-icon"><MapPin size={22} /></div><span className="mini-label">FIND US</span><address>Shop No. 1, Shrushree Apartment,<br />Chowk, Rameshwadi,<br />Badlapur West</address><a className="direction-link" href="https://www.google.com/maps/search/?api=1&query=Shop+No+1+Shrushree+Apartment+Chowk+Rameshwadi+Badlapur+West" target="_blank" rel="noreferrer">GET DIRECTIONS <ArrowUpRight size={15} /></a><p><Clock3 size={15} /> Hours and phone details coming soon</p></div></section>
    <footer className="ig-footer"><a className="ig-brand" href="#top"><span className="ig-mark"><img src="/manus-storage/aone-mark_e21acb3f.png" alt="" /></span><span>A ONE</span></a><span>MORE CARE, MORE BEAUTY, MORE CONFIDENCE.</span><a href="https://www.instagram.com/aone_salon_spa/" target="_blank" rel="noreferrer"><Instagram size={17} /> @aone_salon_spa</a></footer>
  </main>;
}
